apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"user-service","namespace":"ecommerce"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"user-service"}},"template":{"metadata":{"labels":{"app":"user-service"}},"spec":{"containers":[{"env":[{"name":"SPRING_CLOUD_CONFIG_NAME","value":"user-service"},{"name":"SPRING_PROFILES_ACTIVE","value":"dev"},{"name":"SPRING_ZIPKIN_BASE_URL","valueFrom":{"configMapKeyRef":{"key":"ZIPKIN_BASE_URL","name":"zipkin-config"}}},{"name":"EUREKA_CLIENT_SERVICEURL_DEFAULTZONE","valueFrom":{"configMapKeyRef":{"key":"EUREKA_SERVER_URL","name":"eureka-config"}}},{"name":"EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE","valueFrom":{"configMapKeyRef":{"key":"EUREKA_SERVER_URL","name":"eureka-config"}}},{"name":"EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE","valueFrom":{"configMapKeyRef":{"key":"EUREKA_SERVER_URL","name":"eureka-config"}}},{"name":"SPRING_CONFIG_IMPORT","value":"optional:configserver:http://cloud-config-service:9296/"},{"name":"SPRING_CLOUD_CONFIG_URI","value":"http://cloud-config-service:9296"},{"name":"EUREKA_INSTANCE_PREFER_IP_ADDRESS","value":"true"},{"name":"EUREKA_INSTANCE_HOSTNAME","value":"user-service"},{"name":"EUREKA_CLIENT_ENABLED","value":"true"},{"name":"EUREKA_CLIENT_FETCH_REGISTRY","value":"true"},{"name":"RIBBON_EUREKA_ENABLED","value":"true"}],"image":"selimhorri/user-service-ecommerce-boot:0.1.0","imagePullPolicy":"IfNotPresent","name":"user-service","ports":[{"containerPort":8700,"name":"http"}],"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}]}}}}
  creationTimestamp: "2025-10-31T02:45:59Z"
  generation: 5
  name: user-service
  namespace: ecommerce
  resourceVersion: "44665"
  uid: b6742a0b-233d-40e1-a7d2-d2f4f6fe4341
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: user-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-11-01T19:08:08-05:00"
      labels:
        app: user-service
    spec:
      containers:
      - env:
        - name: SPRING_CLOUD_CONFIG_NAME
          value: user-service
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: SPRING_ZIPKIN_BASE_URL
          value: http://zipkin-service.ecommerce:9411/
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              key: EUREKA_SERVER_URL
              name: eureka-config
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://service-discovery-service.ecommerce:8761/eureka
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
          valueFrom:
            configMapKeyRef:
              key: EUREKA_SERVER_URL
              name: eureka-config
        - name: SPRING_CONFIG_IMPORT
          value: optional:configserver:http://cloud-config-service.ecommerce:9296
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://cloud-config-service:9296
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: user-service
        - name: EUREKA_CLIENT_ENABLED
          value: "true"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "true"
        - name: RIBBON_EUREKA_ENABLED
          value: "true"
        image: selimhorri/user-service-ecommerce-boot:0.1.0
        imagePullPolicy: IfNotPresent
        name: user-service
        ports:
        - containerPort: 8700
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-11-03T14:11:56Z"
    lastUpdateTime: "2025-11-03T14:11:56Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-31T02:45:59Z"
    lastUpdateTime: "2025-11-03T18:01:49Z"
    message: ReplicaSet "user-service-847f67b5d6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
